menu:
- {name: 'people', url: '/people'}
- {name: 'research', url: '/research'}
- {name: 'publications', url: '/publications'}
- {name: 'join us', url: '/joinus'}
- {name: 'contact', url: '/contact'}



research:
- {name: 'Neural mechanisms of cognitive control', image: 'assets/img/research/direction1.png', mdfile: 'direction1.md'}
  
- {name: 'Cognitive control in silico', image: 'assets/img/research/direction2.png', mdfile: 'direction2.md'}

- {name: 'Neuromodulation', image: 'assets/img/research/direction3.png', mdfile: 'direction3.md'}

people:
- {name: 'Zhongzheng Fu, Ph.D.', title: 'Principal Investigator', department: 'Neurological Surgery', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'zhongzheng.fu AT utsouthwestern.edu', office: 'Science Building 505', image: 'assets/img/profile.jpg', url: 'primary-investigator', mdfile: 'FuZ.md'}
- {name: 'Ze Geng', title: 'Graduate Student', department: 'Neurological Surgery', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'ze.geng AT utsouthwestern.edu', office: 'Science Building 505', image: 'assets/img/zeG.jpg', url: 'lab-technician', mdfile: 'GengZ.md'}
- {name: 'Sophia Pouya', title: 'Research Assistant', department: 'Neurological Surgery', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'sophia.pouya AT utsouthwestern.edu', office: 'Science Building 505', image: 'assets/img/sophiaP.jpg', url: 'graduate-student', mdfile: 'SophiaP.md'}



courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'twitter', link: 'https://twitter.com/brooksfu_neuro'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/zhongzheng-brooks-fu-a5935121/'}

contacts:
- {name: 'Zhongzheng Fu, Ph.D.', title: 'Assistant Professor', department: 'Neurological Surgery', institution: 'UT Southwestern Medical Center', institution_address: '5303 Harry Hines Blvd., Dallas, TX 75390', phone: '(214) 648-3884', email: 'Zhongzheng.Fu AT UTSouthwestern.edu', office: 'Sprague Clinical Science Building', image: 'assets/img/sprague.jpeg'}
